config/routes.rb
Careerfairs::Application.routes.draw do

  resources :guests
  match 'guests/:id/validGuest' => "guests#validGuest"
  match 'guests/:id/refuseGuest' => "guests#refuseGuest"
  match 'guests/:id/reinitializeGuest' => "guests#reinitializeGuest"

  resources :sites
  resources :pages

  resources :events do
    resources :stands
    resources :guests , :only => [:create, :index, :new]
    resources :companies, :only => [:index]
    match 'documents' => 'events#documents'
  end

  resources :contacts
  
  resources :companies do
    resources :contacts
  end


  match 'companytoevents/list' => 'companytoevents#list', :as => 'companytoevents_list'
  resources :companytoevents

  resources :companytoevents do
    resources :badges
    resources :jobs
    resources :events
  end

  resources :badges, :only => [:destroy, :update]
  resources :jobs, :only => [:destroy, :update]
  resources :stands, :only => [:destroy, :update]

  match 'sessions/logout' => 'sessions#logout'
  match 'sessions/new' => 'sessions#login'
  match 'sessions' => 'sessions#create', :via => :post  
  match 'sessions/:contact_id/become' => 'sessions#become#:contact_id', :via => :get, :as => :become_contact

  match 'events/:event_id/companies/:company_id/subscribe' => 'companies#subscribe',  :via => :get, :as => :event_subscribe
  match 'events/:event_id/companies/:company_id/unsubscribe' => 'companies#unsubscribe',  :via => :get, :as => :event_unsubscribe

  root :to => 'events#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_secure_password

  belongs_to :company
  attr_accessible :name, :login, :password, :password_confirmation, :email, :phone, :company_id
  
  validates :password, :presence => { :on => :create }
  #validates :email, :presence => true, :uniqueness => true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  def index
    if params[:company_id].present?
      if params[:search].present?
        @search = Contact.where("company_id = " + params[:company_id]).search(params[:search])
        @contacts = @search.paginate(:page => params[:page], :per_page => 10)   # or @search.relation to lazy load in view // @search.paginate(:page => params[:page])
      else
        @contacts = Contact.where("company_id = " + params[:company_id]).paginate(:page => params[:page], :per_page => 10)
      end
    else
      flash[:error] = 'No contact was found.' 
    end
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /companies/:company_id/contacts/:id(.:format)
  def show
    @contact = Contact.find(params[:id])
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  def create
    @contact = Contact.new(params[:contact])

    if @contact.save
      redirect_to company_contacts_url(Contact.find(session[:current_user_authenticated]).company_id), notice: 'Contact was successfully created.' 
    else
      render action: "new" 
    end
  end

  # PUT /contacts/1
  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(params[:contact])
      redirect_to company_contacts_url(Contact.find(session[:current_user_authenticated]).company_id), notice: 'Contact was successfully updated.'
    else
      render action: "edit" 
    end
  end

  # DELETE /contacts/1
  def destroy
    @contact = Contact.find(params[:id])
    company_id = @contact.company_id
    @contact.destroy

    redirect_to company_contacts_url(Contact.find(session[:current_user_authenticated]).company_id)
  end
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, :html => { :class => "form-horizontal"}) do |f| %>

  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="control-group">
    <%= f.label :contact_name, :class => "control-label", :for => "contact_name" %>
    <div class="controls">
      <%= f.text_field :name, :placeholder => 'Contact name' %>
    </div>
  </div>  

  <div class="control-group">
    <%= f.label :contact_email, :class => "control-label", :for => "contact_email" %>
    <div class="controls">
      <%= f.text_field :email, :placeholder => 'Contact email' %>
    </div>
  </div>  

  <div class="control-group">
    <%= f.label :contact_phone, :class => "control-label", :for => "contact_phone" %>
    <div class="controls">
      <%= f.text_field :name, :placeholder => 'Contact phone number' %>
    </div>
  </div>  

  <div class="control-group">
    <%= f.label :password, :class => "control-label", :for => "contact_password" %>
    <div class="controls">
      <%= f.password_field :password %>
    </div>
  </div>  

  <div class="control-group">
    <%= f.label :password_confirmation, :class => "control-label", :for => "contact_password_confirmation" %>
    <div class="controls">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>


  <%= f.hidden_field :company_id, :value => params[:company_id] %>
  <%= f.submit :class => "btn btn-primary btn-normal" %>

<% end %> 

<% 
      # t.integer :company_id
      # t.string :password
%>

app/views/contacts/edit.html.erb
<legend>Update Contact</legend>

<fieldset>
	<%= render 'form' %>
</fieldset>

app/views/contacts/index.html.erb
<div class="container-fluid">

  <%= link_to 'New Contact', new_company_contact_path, :class => "btn btn-primary" %>

  <%= form_tag company_contacts_path, :method => :get, :id => 'contact_search', :class => "navbar-search pull-right visible-desktop" do %>
      <%= text_field_tag 'search[name_or_login_or_email_contains]', nil, :class => "search-query", :placeholder => "Contact name, email or login" %>

  <% end %>

  <br /><br /><hr /><br />

  <% @contacts.each do |contact| %>
      <div class="table table-hover">
      <div class="row-fluid ">

        <div class="span12">
          <h4><%= contact.name %></h4>
        </div>  

      </div>
      <div class="row-fluid">
        
        <div class="span9">
          Email : <%= contact.email %> <br />
          Phone :  <%= contact.phone %>
        </div>

          <div class="span3">
            <div class="btn-group" data-toggle="buttons-checkbox" style="text-align: center;">
              <%= link_to 'Edit', edit_company_contact_path(contact.company, contact), :class => "btn btn-warning " %> 
              <%= link_to 'Become', become_contact_path(contact.id), :class => "btn btn-notice " %> 
              <%= link_to 'Destroy', [contact.company, contact], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
            </div>
          </div>
      </div>

      <hr />
    
    </div>
  <% end %>

  <div class="flickr_pagination pagination-centered">
    <%= will_paginate @contacts, :class => "flickr_pagination"  %>
  </div>
</div>

app/views/contacts/new.html.erb
<legend>New Contact For Company </legend>

<fieldset>
	<%= render 'form' %>
</fieldset>