config/routes.rb
Careerfairs::Application.routes.draw do

  resources :guests
  match 'guests/:id/validGuest' => "guests#validGuest"
  match 'guests/:id/refuseGuest' => "guests#refuseGuest"
  match 'guests/:id/reinitializeGuest' => "guests#reinitializeGuest"

  resources :sites
  resources :pages

  resources :events do
    resources :stands
    resources :guests , :only => [:create, :index, :new]
    resources :companies, :only => [:index]
    match 'documents' => 'events#documents'
  end

  resources :contacts
  
  resources :companies do
    resources :contacts
  end


  match 'companytoevents/list' => 'companytoevents#list', :as => 'companytoevents_list'
  resources :companytoevents

  resources :companytoevents do
    resources :badges
    resources :jobs
    resources :events
  end

  resources :badges, :only => [:destroy, :update]
  resources :jobs, :only => [:destroy, :update]
  resources :stands, :only => [:destroy, :update]

  match 'sessions/logout' => 'sessions#logout'
  match 'sessions/new' => 'sessions#login'
  match 'sessions' => 'sessions#create', :via => :post  
  match 'sessions/:contact_id/become' => 'sessions#become#:contact_id', :via => :get, :as => :become_contact

  match 'events/:event_id/companies/:company_id/subscribe' => 'companies#subscribe',  :via => :get, :as => :event_subscribe
  match 'events/:event_id/companies/:company_id/unsubscribe' => 'companies#unsubscribe',  :via => :get, :as => :event_unsubscribe

  root :to => 'events#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :contacts
	has_many :stands
	has_many :companytoevents
	has_many :events, :through => :companytoevents
	has_many :badges, :through => :companytoevents
	has_many :jobs, :through => :companytoevents

	attr_accessible :name, :description, :address, :website, :formlocked, :badgeslocked, :lunch, :pic, :comment

	has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>"}

	validates_attachment_content_type :pic, :content_type => ['image/jpeg', 'image/png','image/gif']
    
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :require_admin_right, :only => [:index, :new, :create, :destroy]
  before_filter :require_company_right

  # GET /companies
  def index
    if params[:search].present?
      @search = Company.search(params[:search])
      @companies = @search.paginate(:page => params[:page], :per_page => 10)   # or @search.relation to lazy load in view // @search.paginate(:page => params[:page])
    elsif params[:event_id].present?
      @companies =
    else
      @companies = Company.where("", params[:event_id]).paginate(:page => params[:page], :per_page => 10)
    end
    @events = Event.where("date_event > ?", DateTime.now)
    @companytoevent = Companytoevent.new

  end

  # GET /companies/1
  def show
    @company = Company.find(params[:id])
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  def create
    @company = Company.new(params[:company])

    if @company.save
      redirect_to companies_url, notice: 'Company was successfully created.' 
    else
      render action: "new" 
    end
  end

  # PUT /companies/1
  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(params[:company])
      redirect_to companies_url, notice: 'Company was successfully updated.'
    else
      render action: "edit" 
    end
  end

  # DELETE /companies/1
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to companies_url
  end

  # SUBSCRIBE /events/1/companies/1/subscribe
  def subscribe
    companytoevent = Companytoevent.new
    companytoevent.event_id = params[:event_id]
    companytoevent.company_id = params[:company_id]
    if companytoevent.save
      redirect_to event_companies_url params[:event_id], notice: 'Company was successfully subscribed.'
    else
      redirect_to event_companies_url params[:event_id], notice: 'Company was not successfully subscribed.'
    end
  end

  # UNSUBSCRIBE /events/1/companies/1/unsubscribe
  def unsubscribe
    companytoeventlist = Companytoevent.where("company_id = ? and event_id = ?", params[:company_id], params[:event_id])
    companytoevent = companytoeventlist.first

    if companytoevent.destroy
      redirect_to event_companies_url params[:event_id], notice: 'Company was successfully unsubscribed.'
    else
      redirect_to event_companies_url params[:event_id], notice: 'Company was not successfully unsubscribed.'
    end
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, :html => { :class => "form-horizontal", :multipart => true}) do |f| %>

  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
        <label class="control-label" id="company_title"> <strong>Name: </strong></label>  
        <div class="controls">
            <%= f.text_field :name, :class => 'span10', :placeholder => 'Company name' %>
        </div>
  </div>
  <div class="control-group">
        <label class="control-label" id="company_body"><strong>Description: </strong></label> 
        <div class="controls">  
          <%= f.text_area :description, :class => 'span10 tinymce', :placeholder => 'Company description' %> 
        </div>
  </div>
  <div class="control-group">
        <label class="control-label" id="company_title"><strong>Adresse: </strong> </label> 
        <div class="controls">  
           <%= f.text_field :address, :class => 'span10', :placeholder => 'Company address' %> 
        </div>
  </div>
  <div class="control-group">
        <label class="control-label" id="company_website"><strong>Website:  </strong> </label> 
        <div class="controls">  
           <%= f.text_field :website, :class => 'span10', :placeholder => 'Company website' %>
        </div>
  </div>

  <% if session[:current_user_admin].present? %>
    <div class="control-group">
          <label class="control-label" id="company_body"><strong>Comment:  </strong> </label> 
          <div class="controls">  
             <%= f.text_area :comment, :class => 'span10 tinymce', :placeholder => 'Comment (only for admin)' %>
          </div>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label" id="company_logo"><strong>Picture:  </strong> </label> 
    <div class="controls">  
      <div class="fileupload fileupload-new" data-provides="fileupload">
          <div class="input-append">
            <div class="uneditable-input span3">
              <i class="icon-file fileupload-exists"></i>
              <span class="fileupload-preview"></span>
            </div>
            <span class="btn btn-file">
            <span class="fileupload-new">Select file</span>
            <span class="fileupload-exists">Change</span>
              <input type="file">
            </span>
            <a class="btn fileupload-exists" data-dismiss="fileupload" href="#">Remove</a>
          </div>
        </div>
    </div>
  </div>

  <div class="control-group">        
        <div class="controls">  
           <%= f.submit :class => "btn btn-primary btn-normal" %>
        </div>
  </div>
  
  
<% end %> 

<% # I need to add :formlocked, :badgeslocked, :lunch, :logo%>

app/views/companies/edit.html.erb
<legend>Update Company</legend>

<fieldset>
	<%= render 'form' %>
</fieldset>

app/views/companies/index.html.erb
<div class="container-fluid">

  <%= link_to 'New Company', new_company_path, :class => 'btn btn-primary' %>

  <%= form_tag companies_path, :method => :get, :id => 'company_search', :class => 'navbar-search pull-right visible-desktop' do %>
      <%= text_field_tag 'search[name_or_comment_contains]', nil, :class => 'search-query', :placeholder => 'Company or comment' %>
  <% end %>

  <br/><br/>
  <hr/>
  <br/>

  <legend>Companies</legend>

  <% @companies.each do |company| %>
      <div class="table table-hover">
        <div class="row-fluid">
          <div class="span12">
            <h4><%= company.name %></h4>
          </div>
        </div>
        <div class="row-fluid">

          <div class="span8">
            <i class="icon-comment"></i> <%= company.comment %> <br/>
            <% @events.each do |event| %>
                <% if event.in? company.events %>
                    <span class="label label-success">Event <%= event.event_name %> </span>
                    <%= link_to 'unsubscribe', event_unsubscribe_url(event.id,company.id), :class => 'btn-small btn-danger' %>
                <% else %>
                    <span class="label label-important">Event <%= event.event_name %> </span>
                    <%= link_to 'subscribe', event_subscribe_url(event.id,company.id), :class => 'btn-small btn-success' %>
                <% end %>
                <br/>
            <% end %>
          </div>

          <div class="span4">

            <%= link_to 'See Contacts', company_contacts_url(company.id), :class => 'btn btn-info ' %>
            <%= link_to 'Destroy', company, method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>

          </div>
        </div>
        <br/>
        <hr/>

      </div>
  <% end %>


  <div class="flickr_pagination pagination-centered">
    <%= will_paginate @companies, :class => 'flickr_pagination' %>
  </div>
</div>

app/views/companies/new.html.erb
<legend>New Company</legend>

<fieldset>
	<%= render 'form' %>
</fieldset>

app/views/companies/show.html.erb
<div class="container-fluid">
	<div class="span12">
		<div class="row-fluid">
			<div class="span12">	
				<div class="span2">					
					<%= image_tag @company.pic.url(:medium) %>					
				</div>
				<div class="span9">
					<%= link_to 'Edit this Company', edit_company_path(@company.id), :class => "btn btn-warning " %>
				</div>
			</div>
			<br /><br /><br /><br /><br /><br />
			<div class="row-fluid">	 	
		 		<div class="span2"><strong>Name: </strong></div>
		 		<div class="span6"><%= @company.name %></div> 		
		 	</div>
		 	<div class="row-fluid">
		 		<div class="span2"></i><strong>Adresse: </strong></div>
		 		<div class="span6"><%= @company.address %></div> 		
		 	</div>
		 	<div class="row-fluid">
		 		<div class="span2"><strong>Website: </strong></div>
		 		<div class="span6"><%= link_to @company.website, @company.website , :target => "_blank"%></div> 		
		 	</div>
		 	<div class="row-fluid">
		 		<div class="span2"><strong>Description: </strong></div>
		 		<div class="span9"><%= @company.description %></div> 		
		 	</div>
		 	<div class="row-fluid">
		 		<div class="span2"><strong>Contacts: </strong></div>
		 		<div class="span6"><%= @company.contacts.count %></div> 		
		 	</div>						
		</div>
	</div>
		
</div>

 