config/routes.rb
Careerfairs::Application.routes.draw do

  resources :guests
  match 'guests/:id/validGuest' => "guests#validGuest"
  match 'guests/:id/refuseGuest' => "guests#refuseGuest"
  match 'guests/:id/reinitializeGuest' => "guests#reinitializeGuest"

  resources :sites
  resources :pages

  resources :events do
    resources :stands
    resources :guests , :only => [:create, :index, :new]
    resources :companies, :only => [:index]
    match 'documents' => 'events#documents'
  end

  resources :contacts
  
  resources :companies do
    resources :contacts
  end


  match 'companytoevents/list' => 'companytoevents#list', :as => 'companytoevents_list'
  resources :companytoevents

  resources :companytoevents do
    resources :badges
    resources :jobs
    resources :events
  end

  resources :badges, :only => [:destroy, :update]
  resources :jobs, :only => [:destroy, :update]
  resources :stands, :only => [:destroy, :update]

  match 'sessions/logout' => 'sessions#logout'
  match 'sessions/new' => 'sessions#login'
  match 'sessions' => 'sessions#create', :via => :post  
  match 'sessions/:contact_id/become' => 'sessions#become#:contact_id', :via => :get, :as => :become_contact

  match 'events/:event_id/companies/:company_id/subscribe' => 'companies#subscribe',  :via => :get, :as => :event_subscribe
  match 'events/:event_id/companies/:company_id/unsubscribe' => 'companies#unsubscribe',  :via => :get, :as => :event_unsubscribe

  root :to => 'events#index'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

<% if params[:notice].is_a?(String) %>
    <div class="alert alert-notice">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, params[:notice], :id => "flash_notice" %>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-inverse navbar-static-top">
  <nav class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "CB Careerfairs - " + Event.find(session[:current_event]).event_name, root_path, :class => 'brand' %>

      <div class="nav-collapse">
        <ul class="nav">

          <li class="dropdown">
            <a href="/events" class="dropdown-toggle" data-toggle="dropdown"><%= t(:manage_events)%> <b class="caret"></b></a>
            <ul class="dropdown-menu">

              <li class="dropdown-submenu">
                <a tabindex="-1" href="<%= event_path(session[:current_event]) %>">
                  <i class="icon-home"></i> <%= Event.find(session[:current_event]).event_name %></a>
                <ul class="dropdown-menu">
                  <% @events.each do |ev| %>
                    <li><%= link_to ev.event_name, event_url(ev.id) %></li>
                  <% end %>
                </ul>
              </li>
              <li></li>
              <li><%= link_to "Update this Event", edit_event_url(session[:current_event]) %></li>
              <li><%= link_to "Manage the documents", event_url(session[:current_event]) %></li>
              <li><%= link_to "Destroy this Event", Event.find(session[:current_event]), method: :delete, data: { confirm: 'Are you sure?' }, :class=> "text-warning" %></li>
              <li class="divider"></li>

              <li class="nav-header">Companies</li>
              <li><%= link_to "Manage Companies", event_companies_path(session[:current_event]) %></li>
              <li></li>
              <li class="divider"></li>

              <li class="nav-header">Guests</li>
              <li><%= link_to "Validation of guests", event_guests_path(session[:current_event])%></li>
              <li><%= link_to "Export as Excel", event_guests_path(session[:current_event], :format => "xls")%></li>
              <li class="divider"></li>

              <li class="nav-header">Badges</li>
              <li><%= link_to "Manage Badges", "#" %></li>
              <li><%= link_to "Exports Badges", "#"%></li>
              <li class="divider"></li>


              <li class="nav-header">Stands</li>
              <li><%= link_to "Manage Stands", event_stands_url(session[:current_event]) %></li>
              <li class="divider"></li>

              <li class="nav-header">Manage Events</li>
              <li><%= link_to "Create a new Event", new_event_path%></li>

            </ul>
          </li>
          <li class="divider-vertical"></li>

          <li class=""><a href="/companies"><%= t(:manage_companies)%></a></li>
          <li class="divider-vertical"></li>

          <li class=""><a href="/mails"><%= t(:manage_mails)%></a></li>
          <li class="divider-vertical"></li>

          <li class=""><a href="/htmlpages"><%= t(:manage_html_pages)%></a></li>
          <li class="divider-vertical"></li>

          <li class="">
          <% if session[:current_user_authenticated].nil? %>
            <a href="/sessions/new"><%= t(:login)%></a>
          <% else %>
            <p class="navbar-text">
              Hello <%= Contact.find(session[:current_user_authenticated]).name %>
              <% if session[:current_user_admin] %>
                <span class="label label-important">ADMIN</span>
              <% end %>
              <em>(<a href="/sessions/logout"><%= t(:logout)%></a>)</em>
            </p>
          <% end %>
          </li>

        </ul>
      </div>

    </div>
  </nav>
</header>

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><%= link_to params["controller"].capitalize, :controller => params["controller"], :action => "index" %> </li>
  <% if params["action"] != "index" %>
    <li class="active"><span class="divider">/</span><%= link_to params["action"].capitalize, :controller => params["controller"], :action => params["action"] %></li>
  <% end %>
</ul>

app/views/layouts/_navigation_admin.html.erb
<header class="navbar navbar-inverse navbar-static-top">
  <nav class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to Event.find(session[:current_event]).event_name, root_path, :class => 'brand' %>
      <div class="nav-collapse">
        <ul class="nav">

          <li class="dropdown">
            <a href="/events" class="dropdown-toggle" data-toggle="dropdown"><%= t(:manage_event)%> <b class="caret"></b></a>
            <ul class="dropdown-menu">

              <li class="dropdown-submenu">
                <a tabindex="-1" href="<%= event_path(session[:current_event]) %>">
                  <i class="icon-home"></i> <%= Event.find(session[:current_event]).event_name %></a>
                <ul class="dropdown-menu">
                  <% @events.each do |ev| %>
                    <li><%= link_to ev.event_name, event_url(ev.id) %></li>
                  <% end %>
                </ul>
              </li>
              <li><%= link_to "Update this Event", edit_event_url(session[:current_event]) %></li>
              <li><%= link_to "Manage the documents", event_documents_url(session[:current_event]) %></li>
              <li><%= link_to "Destroy this Event", Event.find(session[:current_event]), method: :delete, data: { confirm: 'Are you sure?' }, :class=> "text-warning" %></li>
              <li class="divider"></li>

              <li><%= link_to t(:manage_stands), event_stands_url(session[:current_event]) %></li>
              <li class="divider"></li>

              <li><%= link_to t(:create_new_event), new_event_path%></li>

            </ul>
          </li>
          <li class="divider-vertical"></li>

          <li class="dropdown">
            <a href="/events" class="dropdown-toggle" data-toggle="dropdown"><%= t(:manage_companies)%> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Company", event_companies_path(session[:current_event]) %></li>
              <li><%= link_to "Manage Companies", event_companies_path(session[:current_event]) %></li>
            </ul>
          </li>
          <li class="divider-vertical"></li>

          <li class="dropdown">
            <a href="/events" class="dropdown-toggle" data-toggle="dropdown"><%= t(:manage_guests)%> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Validation of guests", event_guests_path(session[:current_event])%></li>
              <li><%= link_to "Export as Excel", event_guests_path(session[:current_event], :format => "xls")%></li>
            </ul>
          </li>
          <li class="divider-vertical"></li>

          <li class="dropdown">
            <a href="/events" class="dropdown-toggle" data-toggle="dropdown"><%= t(:features)%> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t(:manage_features), companytoevents_list_path %></li>
            </ul>
          </li>
          <li class="divider-vertical"></li>

          <li class="dropdown">
            <a href="/events" class="dropdown-toggle" data-toggle="dropdown"><%= t(:badges)%> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t(:manage_badges), "#" %></li>
              <li><%= link_to t(:export_badges), "#"%></li>
            </ul>
          </li>
          <li class="divider-vertical"></li>

          <li class="dropdown">
            <a href="/events" class="dropdown-toggle" data-toggle="dropdown"><%= t(:manage_content)%> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/mails"><%= t(:manage_mails)%></a></li>
              <li><a href="/pages"><%= t(:manage_html_pages)%></a></li>
            </ul>
          </li>
          <li class="divider-vertical"></li>

          <li class="">
            <p class="navbar-text">
              <span class="label label-important">ADMIN</span><em>(<a href="/sessions/logout"><%= t(:logout)%></a>)</em>
            </p>
          </li>

        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/_navigation_company.html.erb
<header class="navbar navbar navbar-static-top">
  <nav class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
     <!-- <%= link_to Contact.find(session[:current_user_authenticated]).company.name, root_path, :class => 'brand' %> -->
      <div class="nav-collapse">
        <ul class="nav">

          <li class="dropdown">
            <a href="/events" class="dropdown-toggle brand" data-toggle="dropdown"> <%= Event.find(session[:current_event]).event_name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% @events.each do |ev| %>
                <li><%= link_to ev.event_name, event_url(ev.id) %></li>
              <% end %>
            </ul>
          </li>
          
          <li class="divider-vertical"></li>

          <li><%= link_to "Manage Information", company_path(Contact.find(session[:current_user_authenticated]).company_id) %></li>
          <li class="divider-vertical"></li>

          <!--definit dans le application_helper.erb-->
          <li><%= link_to "Manage features", companytoevents_path() %></li>
          <li class="divider-vertical"></li>

          <li><%= link_to "Manage Badges", companytoevent_badges_path(session[:current_companytoevent_id]) %></li>
          <li class="divider-vertical"></li>

          <li><%= link_to "Manage Jobs", companytoevent_jobs_path(session[:current_companytoevent_id]) %></li>
          <li class="divider-vertical"></li>

          <li class="">
            <p class="navbar-text">
              Hello <%= Contact.find(session[:current_user_authenticated]).name %>
              <em>(<a href="/sessions/logout"><%= t(:logout)%></a>)</em>
            </p>
          </li>

        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Careerfairs" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <% if session[:current_user_admin].present? %>
      <%= render 'layouts/navigation_admin' %>
    <% end %>
    <% if session[:current_user_authenticated].present? %>
      <%= render 'layouts/navigation_company' %>
    <% end %>
    <%= render 'layouts/breadcrumb' %>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->

    <br /><br /><br />
    <hr />
    <pre>
      Session:<%=session%>.
      Params:<%=params%>.
      Event : <%=session[:current_event]%>
      <% if session[:current_user_authenticated].present? %>
          Contact : <%=Contact.find(session[:current_user_authenticated]).id%>
          Company : <%=Contact.find(session[:current_user_authenticated]).company.id%>
      <% end %>
    </pre>

  </body>
</html>

app/views/layouts/blank.html.erb
<%= yield %>